<a href="https://colab.research.google.com/github/Hikmee/ML/blob/master/Modern_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Dictionary**

In [ ]:

from typing import Dict , Union
import pprint # to print objects dict etc in a decent way

In [ ]:
Key: Union[str,int] #custom type
Value: Union[str, tuple, set ] # custom types
data: Dict[str , str] ={"name":"hikmat" , "fname":"Sibghat"}
data
pprint.pprint(data)
print(data["name"]) # key should be passed as we have puted in dictionary like string in dict so will pas as str

{'fname': 'Sibghat', 'name': 'hikmat'}
hikmat


Note: Hashable means unique identification that can't be changed.

key type should be hashable
like we can't use list key and we can make tuple a key because it's hashable(immutable)

In [ ]:
#type casting

abc: set = {1,2,3,4,}
x : list[int] = list(abc)
print(x)

[1, 2, 3, 4]


**SET data type:**
data: set = {1,2,3,3,}
note: we can't apply atration on set data type , for that we use typecasting
NOTE: set takes dta nique, or it holds the unique data

In [ ]:
#value addition in dict

data["name"] = "Qudrat"

In [ ]:
print(data.get("name" , "NA")) # if key will be available so it will give the vauw if not availabe than not give an error , here will give na

Qudrat


**data.keys** will give all keys
**data.values** will give all values in dictionary
**data.items** will give us both key and value of a dictionary in the orm of typle
Note: all above are generator function means to execute it we should have to write it in for/ist loop


In [ ]:
{k : v for k,v in data.items()} # unzip the dictionay
# we can also shufle keys and values by list comprehensive
{v : k for k,v in data.items()}

Key: Union[str,int]
keys:list[str] = ['name' , 'fname' , 'ID']
data:dict[Key,Value]={}
print(data)

ndata=data.fromkeys(keys) # this will add list to the dict as key , if key will not be present then we can print a default value like NA as well
print(ndata)




NameError: ignored

**Class08**
24/10/2023

TypeDict is basically used for making long types eg if we make dictionary in list (nested typing),
and we import this from typing

In [ ]:
methods: list[str] = [m for m in dir(data) if "__" not in m]
print(methods) # these all are dictionary methods

['clear', 'copy', 'fromkeys', 'get', 'items', 'keys', 'pop', 'popitem', 'setdefault', 'update', 'values']


In [ ]:
import pandas as pd
from typing import Any

In [ ]:
students_data:Dict[str, list[Any]] = {
    "name": ["Hikmat Ullah" , "Qudrat Ullah" , "Hassnain"],
    "Father Name": ["Sibghat Ullah" , "Sibghat Ullah","Sibghat Ullah"],
    "Reg No": ["20pwcse1919" , "20pwcse1919" ,"20pwcse1919"]
}
dataframe: pd.DataFrame =pd.DataFrame(students_data)
print(dataframe)

           name    Father Name       Reg No
0  Hikmat Ullah  Sibghat Ullah  20pwcse1919
1  Qudrat Ullah  Sibghat Ullah  20pwcse1919
2      Hassnain  Sibghat Ullah  20pwcse1919


jsonify method converts the dictionary into json fromat

**Class 09**

**Attretion** <br>

Note: if we perform attretaion on dictionary so by default this gives us keys <br>
we cant directly perform attretion on set

input from user <br>
input function <br>

*   default type = string
<br>sys.argv(for console input in abc.py file) <br>
default type object( means we will receive that what we will put in it)


In [ ]:
input : str = input("enter your name")

console input ( argv)


*   passed in console with file name
*   to use ( import sys)



In [ ]:
import sys
print("line1")
print(sys.argv) # iterative data type , argv type is list


to check methods of any datatype <br>
dir(datatype)

**Controls:**


1.   break
2.   continue
3.   pass ( eg if we write some code and want to write the rest of the code so our program will skip the error here instead giving error)



**Class 09**

Functions


1.   return
2.   non-return



Requaired parameters function

In [ ]:
def addnum(num1 : int , num2 : int) -> int: # function declearation with parameters
  return(num1+num2)

addnum(3,4) # function call with arguments

7

function with optional parameters

In [ ]:
def add_numbr(num1:int , num2:int = 0) -> int:
  print(num1 , num2)
  return num1 + num2

add_numbr(1,5)
add_numbr(1)

1 5
1 0


1

**Lambda function** <br>
one line function <br>
without name function <br>
only use in this line <br>
annonymus function
<br>
**Syntax** <br>
lambda param1,param2:function_body <br>

*NOTE*: we use lambda function for space efficiency <br>
callabe

In [ ]:
a = lambda num1,num2: num1+num2 #lambda function decleration

a(7,8) # function call

15

In [ ]:
data: list[int] = [1,2,3,4,5,6,7,8]

data = list(map(lambda x:x**2 , data)) # we apply attretion (list) because its generator function
data

[1, 4, 9, 16, 25, 36, 49, 64]

In [ ]:
data: list[int] = [1,2,3,4,5,6,7,8]

data = list(filter(lambda x:x%2 == 0 , data)) # we apply attretion (list) because its generator function
data

[2, 4, 6, 8]

**Generator function** <br>
*iterate one by one
<br> *stop after each iteration <br>
*remember old (last) iteration value <br>
*next iterate go forward from that last one

In [ ]:
def my_range(start:int , end:int , step:int):
  for i in range(start , end+1 , step):
    yield i #generator function

a = list(my_range(1,10 , 1))
a


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
from collections.abc import Iterator

def my_range(start:int , end:int , step:int = 1)->Iterator[int]:
  for i in range(start , end+1 , step):
    yield i #generator function

a :Iterator[int]= my_range(1,10 , 1)
print(next(a))
print(next(a))

print(type(a))

for i in a:
  print(i)


1
2
<class 'generator'>
3
4
5
6
7
8
9
10


passing Unlimited arguments


1.   *args
2.   **keyargs



In [ ]:
from typing import Tuple, Dict
def gret(*names: Tuple[str , ...])->None:
  print(f"hello{names}")

**Numpy**

In [1]:
!pip install nptyping beartype

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 819.1/819.1 kB 25.9 MB/s eta 0:00:00


#Scalar type <br>
* NOTE: Scalar has no any dimensions ( zero dimention)

In [3]:
import numpy as np

a: np.ndarray = np.array(1000)
display(a)
display(a.shape)
display(type(a))
display(a.dtype)
display(a.ndim)
display(a.size) # how many bits it consists
display(a.itemsize)

array(1000)

()

numpy.ndarray

dtype('int64')

0

1

8

#Vector type

In [5]:
import numpy as np

a: np.ndarray = np.array([1,2,3,4,5,6,7])
display(a)
display(a.shape)
display(type(a))
display(a.dtype)
display(a.ndim)
display(a.size) # number of elemnts
display(a.itemsize) # how many bits it consists

array([1, 2, 3, 4, 5, 6, 7])

(7,)

numpy.ndarray

dtype('int64')

1

7

8

In [9]:
a.size ?
help(a.itemsize)

SyntaxError: ignored

In [10]:
import numpy as np
data = [[1,2,3],
        [4,5,6],
        [7,8,9]]

a: np.ndarray = np.array(data)
display(a)
display(a.shape)
display(type(a))
display(a.dtype)
display(a.ndim)
display(a.size) # number of elemnts
display(a.itemsize) # how many bits it consists

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

(3, 3)

numpy.ndarray

dtype('int64')

2

9

8

#Numpy with NDArray typing support


In [17]:
from nptyping import NDArray , Shape ,  UInt64
from typing import Any

data : NDArray[Shape["10"] , Any] = np.arange(1,11)
print(data)
print(data+5) # tis operation can't b edone without numpy

[ 1  2  3  4  5  6  7  8  9 10]
[ 6  7  8  9 10 11 12 13 14 15]


In [19]:
%%time

data : NDArray[Shape["10"] , Any] = np.arange(1,10000000)
data + 5

CPU times: user 23.5 ms, sys: 43.7 ms, total: 67.2 ms
Wall time: 68.2 ms


array([       6,        7,        8, ..., 10000002, 10000003, 10000004])

In [20]:
%%time
data: list[int] = list(range(1,1000000))

[i + 5 for i in data]

CPU times: user 124 ms, sys: 44.5 ms, total: 168 ms
Wall time: 415 ms


[6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,


#numpy advanced operations vs list operations

###Normal python

In [21]:
data: list[int] = list(range(1,20))
print(data)
print(data[5:11])
data[5:11] = 100 # ormal python does not allow this

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[6, 7, 8, 9, 10, 11]


TypeError: ignored

In [23]:
ndata: NDArray[Shape["20"], Any] = np.arange(1,21)
print(ndata)
print(ndata[5:11])
ndata[5:11] = 1000 # consider it as changing resolution of images
print(ndata)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 6  7  8  9 10 11]
[   1    2    3    4    5 1000 1000 1000 1000 1000 1000   12   13   14
   15   16   17   18   19   20]


# numpy 1D arrays functions

In [25]:
state_bank: NDArray[Shape["10"] , Any] = np.array([1,7,8,10])
ubl_bank: NDArray[Shape["100"], Any] = np.random.randint(1,1000 , 20) # min , max, number of items

display(state_bank)
display(ubl_bank)

array([ 1,  7,  8, 10])

array([ 33,  95, 182, 311, 873, 154, 835, 544, 885, 458, 220, 335, 161,
       430, 246, 300, 904, 661,  54, 746])

##Bool search in Numpy

In [47]:
from nptyping.typing_ import Bool
import beartype

state_bank: NDArray[Shape["4"] , Any] = np.array([1,7,8,10])
#[1,7,8,10]
#[True , False , False , True]
#variable[True , False , False , True]
select: NDArray[Shape["4"] , Bool] = np.array([True , False , False , True]) # dimention should be same as the NDArray
# # will return in bool array
state_bank[select]
# state_bank[state_bank % 2 == 0]

array([ 1, 10])

In [35]:
display(state_bank)
display(ubl_bank)
np.in1d(state_bank , ubl_bank) # first var items length returned

array([ 1,  7,  8, 10])

array([ 33,  95, 182, 311, 873, 154, 835, 544, 885, 458, 220, 335, 161,
       430, 246, 300, 904, 661,  54, 746])

array([False, False, False, False])

In [36]:
np.intersect1d(state_bank , ubl_bank)

array([], dtype=int64)

In [40]:
ubl_bank: NDArray[Shape["100"], Any] = np.random.randint(1,1000 , 20) # min , max, number of items
hbl_bank: NDArray[Shape["100"], Any] = np.random.randint(1,1000 , 20) # min , max, number of items
display(f"UBL bank: {ubl_bank}")
display(f"HBL bank: {hbl_bank}")
np.where(ubl_bank > hbl_bank , ubl_bank , hbl_bank)  # use for comperison like image resultaion

'UBL bank: [557 705 399 876 613 259 486 925  65 499 723 649 800 819 615 958 770 340\n 395 740]'

'HBL bank: [289 835 117 735 675 342 584 523 444 315 865 908 823 206 965 208  99 912\n 937 909]'

array([557, 835, 399, 876, 675, 342, 584, 925, 444, 499, 865, 908, 823,
       819, 965, 958, 770, 912, 937, 909])

# Create Numpy Array

In [43]:
a: NDArray[Shape["*, *"] , Any] = np.array([[2,3,4] ,
                                                  [5,6,7]])

print(a)

a: NDArray[Shape["* ,*"] , Any] = np.array([[3,4] ,
                                                  [6,7]])
print(a)

a: NDArray[Shape["*, *"] , Any] = np.array([["A"] ,
                                                  ["B"]])
print(a)

[[2 3 4]
 [5 6 7]]
[[3 4]
 [6 7]]
[['A']
 ['B']]


In [44]:
np.who() # tells all variables history that we have created so for

Name            Shape            Bytes            Type

_               20               160              int64
__              20               160              int64
___             20               160              int64
a               2 x 1            8                str32
_19             9999999          79999992         int64
ndata           20               160              int64
state_bank      4                32               int64
ubl_bank        20               160              int64
select          4                32               int64
_27             4                4                bool
_29             4                4                bool
_30             10               10               bool
_31             4                4                bool
_32             2                16               int64
_33             4                4                bool
_34             4                4                bool
_35             4                4                bool

In [45]:
a: NDArray[Shape["Size, Size"] , Any] = np.arange(3*3).reshape(3,3)

print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [46]:
a: NDArray[Shape["Size, Size , Size"] , Any] = np.arange(2*3*3).reshape(2,3,3)

print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
